# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - agrosmartai

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_196bfe5ffdf649c6bc7f975d61113e90 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_977df551bb3f4894803c9401fb0a2306 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_196bfe5ffdf649c6bc7f975d61113e90 }}/fo0d/agrosmartai:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'agrosmartai'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0c3b7f63b4624ac1b19d101646e037fa }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_196bfe5ffdf649c6bc7f975d61113e90 }}/fo0d/agrosmartai:${{ github.sha }}'